# Generated by Django 5.0.6 on 2024-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
