# Generated by Django 5.0.6 on 2024-05-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_list_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_list',
            name='is_paid',
        ),
    ]
