# Generated by Django 5.0.4 on 2024-05-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_list_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='book_data',
            field=models.DateField(),
        ),
    ]
