# Generated by Django 5.0.4 on 2024-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payment_delete_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default=1, upload_to='tour_detail_image/'),
            preserve_default=False,
        ),
    ]
