# Generated by Django 5.0.3 on 2024-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payment_user_tour_user_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='available_seats',
            field=models.IntegerField(default=50),
        ),
    ]
