# Generated by Django 5.0.6 on 2024-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tour_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='book_list',
            name='book_data',
            field=models.DateField(),
        ),
    ]
