# Generated by Django 5.0.4 on 2024-07-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contact_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_form',
        ),
    ]
